"use client";
import {useState} from "react";
import Link from "next/link";
import {addProfessional,addService,assignService,setProfessionalStatus,setServiceStatus} from "./actions";
type Shop={id:string;name:string;slug:string};
type Service={id:string;name:string;price_cents:number;duration_minutes:number;active:boolean};
type Pro={id:string;name:string;active:boolean};
type Apt={id:string;status:string;price_cents:number;starts_at:string;professional_id:string;client_id:string};
type Client={id:string;name:string};
type Cashback={client_id:string;amount_cents:number};
type Referral={id:string;referrer_client_id:string;status:string};
export default function PainelOperacional({shop,services,professionals,appointments,clients,cashback,referrals,ceo=false}:{shop:Shop;services:Service[];professionals:Pro[];appointments:Apt[];clients:Client[];cashback:Cashback[];referrals:Referral[];ceo?:boolean}){
 const [section,setSection]=useState("overview");
 const paid=appointments.filter(a=>a.status==="completed"),revenue=paid.reduce((v,a)=>v+a.price_cents,0);
 const balance=new Map<string,number>();cashback.forEach(c=>balance.set(c.client_id,(balance.get(c.client_id)||0)+c.amount_cents));
 const money=(n:number)=>(n/100).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
 const names=new Map(clients.map(c=>[c.id,c.name]));
 return <main className="editor-shell management-page"><div className="editor-top"><div><span className="eyebrow">{ceo?"CEO · ACESSO GLOBAL":"PAINEL DA BARBEARIA"}</span><h1>{shop.name}</h1><p>Serviços, equipe, agendamentos e fidelização em um só lugar.</p></div><div className="ceo-actions"><Link className="button secondary" href={ceo?"/ceo":"/gestor"}>Voltar</Link><Link className="button secondary" href={"/b/"+shop.slug}>Ver agendamento</Link><Link className="button primary" href={ceo?"/ceo/empresa/"+shop.id+"/aparencia":"/gestor/aparencia"}>Personalizar</Link></div></div>
 <nav className="manager-tabs">{[["overview","Dashboard"],["team","Serviços e barbeiros"],["loyalty","Cashback e indicações"],["booking","Agendamentos"]].map(([id,label])=><button key={id} type="button" className={section===id?"active":""} onClick={()=>setSection(id)}>{label}</button>)}<Link className="button secondary" href={ceo?"/ceo/empresa/"+shop.id+"/horarios":"/gestor/horarios"}>Horários de funcionamento</Link></nav>
 {section==="overview"&&<div className="kpis"><div className="kpi"><span>Atendimentos concluídos</span><strong>{paid.length}</strong></div><div className="kpi"><span>Faturamento registrado</span><strong>{money(revenue)}</strong></div><div className="kpi"><span>Clientes cadastrados</span><strong>{clients.length}</strong></div><div className="kpi"><span>Indicações</span><strong>{referrals.length}</strong></div></div>
 {section==="team"&&<div className="two-panel"><section className="panel"><h2>Serviços</h2><p>Cadastre nome, preço e duração.</p><form className="manager-form" action={addService}><input type="hidden" name="shop_id" value={shop.id}/><input name="name" placeholder="Nome do serviço" required maxLength={100}/><input name="price" placeholder="Preço em R$" type="number" min="0" step=".01" required/><input name="duration" placeholder="Minutos" type="number" min="5" max="480" required/><button className="button primary">Adicionar serviço</button></form>{services.map(s=><div className="manager-list" key={s.id}><div><strong>{s.name}</strong><p>{money(s.price_cents)} · {s.duration_minutes} min · {s.active?"Ativo":"Inativo"}</p></div><form action={setServiceStatus}><input type="hidden" name="shop_id" value={shop.id}/><input type="hidden" name="id" value={s.id}/><input type="hidden" name="active" value={String(!s.active)}/><button className="button secondary">{s.active?"Desativar":"Ativar"}</button></form></div>)}</section>
 <section className="panel"><h2>Barbeiros</h2><p>Cadastre a equipe e os serviços realizados.</p><form className="manager-form" action={addProfessional}><input type="hidden" name="shop_id" value={shop.id}/><input name="name" placeholder="Nome do barbeiro" required minLength={2} maxLength={100}/><button className="button primary">Adicionar barbeiro</button></form>{professionals.map(p=><div className="manager-list" key={p.id}><div><strong>{p.name}</strong><p>{p.active?"Ativo":"Inativo"} · {paid.filter(a=>a.professional_id===p.id).length} atendimentos concluídos</p></div><form action={setProfessionalStatus}><input type="hidden" name="shop_id" value={shop.id}/><input type="hidden" name="id" value={p.id}/><input type="hidden" name="active" value={String(!p.active)}/><button className="button secondary">{p.active?"Desativar":"Ativar"}</button></form></div>)}{professionals.length>0&&services.length>0&&<form action={assignService} className="manager-form"><h3>Habilitar serviço por barbeiro</h3><input type="hidden" name="shop_id" value={shop.id}/><select name="professional_id">{professionals.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select name="service_id">{services.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><button className="button secondary">Vincular serviço</button></form>}</section></div>
 {section==="loyalty"&&<div className="two-panel"><section className="panel"><h2>Carteira de cashback</h2><p>Saldo acumulado por cliente, em reais. Transações ainda não podem ser lançadas por este painel.</p>{clients.length===0&&<p>Nenhum cliente cadastrado.</p>}{clients.map(c=><div key={c.id} className="manager-list"><strong>{c.name}</strong><strong>{money(balance.get(c.id)||0)}</strong></div>)}</section><section className="panel"><h2>Indicações</h2><p>Quantidade por cliente, com o status de cada indicação.</p>{clients.length===0&&<p>Aguardando indicações.</p>}{clients.map(c=><div key={c.id} className="manager-list"><strong>{c.name}</strong><span>{referrals.filter(r=>r.referrer_client_id===c.id).length} indicações</span></div>)}</section></div>
 {section==="booking"&&<section className="panel"><h2>Últimos atendimentos</h2><div className="table-wrap"><table><thead><tr><th>Data</th><th>Cliente</th><th>Barbeiro</th><th>Status</th><th>Valor</th></tr></thead><tbody>{appointments.map(a=><tr key={a.id}><td>{new Date(a.starts_at).toLocaleString("pt-BR")}</td><td>{names.get(a.client_id)||"Cliente"}</td><td>{professionals.find(p=>p.id===a.professional_id)?.name||"—"}</td><td>{a.status}</td><td>{money(a.price_cents)}</td></tr>)}</tbody></table></div>{appointments.length===0&&<p>Nenhum atendimento registrado.</p>}</section>}</main>
}
