"use client";
import {use, useCallback, useEffect, useState} from "react";
import Link from "next/link";
import {createClient} from "@supabase/supabase-js";
import {ArrowLeft,ArrowRight,Scissors,CheckCircle2} from "lucide-react";
type Svc={id:string;name:string;price_cents:number;duration_minutes:number};
type Pro={id:string;name:string;photo_url?:string};
type Catalog={shop:{name:string;slug:string;primary_color:string};services:Svc[];professionals:Pro[]};
const url=process.env.NEXT_PUBLIC_SUPABASE_URL;
const key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
const db=url&&key?createClient(url,key):null;
function normalizePhone(s:string){const raw=s.replace(/\D/g,"");return raw.length===11||raw.length===10?"+55"+raw:raw.startsWith("55")&&raw.length>=12?("+"+raw):""}
function localToday(){const now=new Date();return [now.getFullYear(),String(now.getMonth()+1).padStart(2,"0"),String(now.getDate()).padStart(2,"0")].join("-")}
export default function Booking({params}:{params:Promise<{slug:string}>}){
 const {slug}=use(params);
 const [catalog,setCatalog]=useState<Catalog|null>(null),[loadError,setLoadError]=useState("");
 const [step,setStep]=useState(0),[name,setName]=useState(""),[phone,setPhone]=useState("");
 const [service,setService]=useState(""),[pro,setPro]=useState(""),[day,setDay]=useState(""),[time,setTime]=useState("");
 const [slots,setSlots]=useState<string[]>([]),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[receipt,setReceipt]=useState("");
 useEffect(()=>{let active=true;(async()=>{if(!db){setLoadError("Agendamento indisponível no momento.");return;}const {data,error}=await db.rpc("booking_catalog",{p_slug:slug});if(!active)return;if(error||!data){setLoadError("Barbearia não encontrada ou indisponível.");return;}setCatalog(data as Catalog)})();return()=>{active=false}},[slug]);
 const svc=catalog?.services.find(x=>x.id===service);
 const proName=catalog?.professionals.find(x=>x.id===pro)?.name;
 const loadSlots=useCallback(async()=>{if(!db||!service||!pro||!day)return;setLoading(true);setTime("");const {data,error}=await db.rpc("booking_slots",{p_slug:slug,p_service:service,p_professional:pro,p_day:day});setSlots(error?[]:(data as string[]||[]));if(error)setError("Não foi possível carregar os horários. Tente novamente.");setLoading(false)},[slug,service,pro,day]);
 useEffect(()=>{void loadSlots()},[loadSlots]);
 async function confirm(){if(!db||!svc||!pro||!time||!day||busy)return;setBusy(true);setError("");const {data,error}=await db.rpc("book_public_appointment",{p_slug:slug,p_service:service,p_professional:pro,p_day:day,p_time:time,p_name:name.trim(),p_phone:normalizePhone(phone)});setBusy(false);if(error){setError("Este horário pode ter sido ocupado ou não está mais disponível. Escolha outro.");await loadSlots();return;}setReceipt(String(data));setStep(3)}
 if(loadError)return <main className="auth-shell"><section className="auth-card"><h1>Agendamento indisponível</h1><p>{loadError}</p><Link className="button secondary" href="/">Voltar</Link></section></main>;
 if(!catalog)return <main className="auth-shell"><p>Carregando agenda...</p></main>;
 return <main className="booking-wrap" style={{"--accent":catalog.shop.primary_color} as React.CSSProperties}>
 <nav className="nav"><Link className="brand" href="/"><Scissors/> Barber<span>Flow</span></Link><Link href="/" className="quiet-link"><ArrowLeft size={16}/> Início</Link></nav>
 <section className="booking-card"><div className="booking-heading"><span className="eyebrow">AGENDAMENTO ONLINE</span><h1>{catalog.shop.name}</h1><p>{step===0?"Informe seus dados para começar.":step===3?"Seu horário foi reservado.":"Escolha seu serviço, profissional e horário."}</p><div className="booking-progress">{["Identificação","Serviço","Horário","Concluído"].map((s,i)=><span key={s} className={step===i?"on":""}>{i+1}. {s}</span>)}</div></div>
 {step===0&&<form className="booking-sections" onSubmit={e=>{e.preventDefault();setError("");setStep(1)}}><div className="fields"><label>Nome completo<input required minLength={2} maxLength={120} value={name} onChange={e=>setName(e.target.value)} autoComplete="name"/></label><label>WhatsApp com DDD<input required inputMode="tel" type="tel" value={phone} onChange={e=>setPhone(e.target.value)} autoComplete="tel" placeholder="(51) 99999-9999"/></label></div><p className="fine-print">O número será utilizado para vincular seu agendamento. O histórico de serviços ficará protegido até a confirmação de posse do WhatsApp.</p>{error&&<p role="alert">{error}</p>}<button type="submit" disabled={name.trim().length<2||!normalizePhone(phone)} className="button primary booking-next">Continuar <ArrowRight size={16}/></button></form>}
 {step===1&&<div className="booking-sections"><div className="step"><h2>Qual serviço deseja agendar?</h2><p className="fine-print">Após a verificação do seu WhatsApp, você também poderá repetir seu último serviço.</p><div className="option-list">{catalog.services.map(s=><button key={s.id} className={"service-option "+(service===s.id?"chosen":"")} onClick={()=>{setService(s.id);setTime("")}}><span><strong>{s.name}</strong><small>{s.duration_minutes} minutos</small></span><b>{(s.price_cents/100).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}</b></button>)}</div></div><div className="step"><h2>Escolha o profissional</h2><div className="chips">{catalog.professionals.map(p=><button className={"chip "+(pro===p.id?"chosen":"")} key={p.id} onClick={()=>{setPro(p.id);setTime("")}}>{p.name}</button>)}</div></div><div className="booking-footer"><button className="button secondary" onClick={()=>setStep(0)}>Voltar</button><button className="button primary" disabled={!service||!pro} onClick={()=>setStep(2)}>Escolher horário <ArrowRight size={16}/></button></div></div>}
 {step===2&&<div className="booking-sections"><div className="step"><h2>{svc?.name} · {proName}</h2><label className="field-label">Escolha a data<input type="date" min={localToday()} value={day} onChange={e=>setDay(e.target.value)}/></label><p className="fine-print">Somente horários disponíveis são exibidos. O sistema confirma a disponibilidade novamente antes de salvar.</p>{loading?<p>Consultando agenda...</p>:<div className="slot-grid">{slots.map(s=><button className={"slot "+(time===s?"chosen":"")} key={s} onClick={()=>setTime(s)}>{s}</button>)}</div>}{day&&!loading&&!slots.length&&<p className="fine-print">Não há horários disponíveis para esta data e profissional.</p>}</div>{error&&<p className="auth-error" role="alert">{error}</p>}<div className="booking-footer"><button className="button secondary" onClick={()=>setStep(1)}>Voltar</button><button className="button primary" disabled={!time||busy} onClick={confirm}>{busy?"Confirmando...":"Confirmar agendamento"} <ArrowRight size={16}/></button></div></div>}
 {step===3&&<div className="booking-sections"><div className="success"><CheckCircle2 size={48}/><h2>Agendamento confirmado</h2><p>{name}, seu {svc?.name} com {proName} está reservado para {day.split("-").reverse().join("/")} às {time}.</p><p className="fine-print">Identificação da reserva: {receipt.slice(0,8)}. Salve esta informação. Notificações por WhatsApp estarão disponíveis futuramente.</p><Link className="button secondary" href="/">Voltar ao início</Link></div></div>}
 </section></main>;
}
